### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by ptrstpp950** [cmatskas/CfpParser#1]
Some dates have wrong format. For example in https://github.com/cmatskas/callForPapers.github.io/commit/6a06c318208096478070ee7b7e5b3b6d2b633acb there is a date 2016-5-17 instead of 2016-05-17

**Comment by cmatskas** [comment]
Lol, I was only kidding but many thanks for raising this. I will try and fix it today :)

**Comment by cmatskas** [comment]
Fixed :)

**Comment by ptrstpp950** [comment]
Cool :)

czw., 25 lut 2016, 12:34 Christos Matskas użytkownik <
notifications@github.com> napisał:
